# Local development orchestration for 3MRAI.
# Run `make help` (the default) to list targets.
# Two layers: docker-compose (Floci + services) and Terraform against Floci.

COMPOSE      := docker compose
TF_LOCAL_DIR := infra/environments/local
TF           := terraform -chdir=$(TF_LOCAL_DIR)
FLOCI_URL    := http://localhost:4566
ENV_FILE     := .env
# Single reusable per-engine RDS-proxy-port discovery. Floci assigns those ports
# (7000-7099) by cluster CREATION ORDER, which is NOT stable across applies, so
# postgres/mysql can flip between 7001/7002. This script reads the port for a
# given engine from `describe-db-clusters` (which exposes Engine per cluster) —
# never hardcode 7001=Postgres / 7002=MySQL. Also used by bootstrap.sh.
DISCOVER_DB_PORT := $(TF_LOCAL_DIR)/scripts/discover-db-port.sh

# Terraform talks to Floci through the host-published port; the AWS provider in
# environments/local/providers.tf pins every endpoint to localhost:4566.
export AWS_ENDPOINT_URL    ?= $(FLOCI_URL)
export AWS_DEFAULT_REGION  ?= us-east-1
export AWS_ACCESS_KEY_ID   ?= test
export AWS_SECRET_ACCESS_KEY ?= test

.DEFAULT_GOAL := help

.PHONY: help up down logs build ps infra-init infra-plan infra-up infra-up-post infra-down infra-output env-file migrate bootstrap clean observability-up observability-down

help: ## List available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "} {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

## --- Docker Compose ---

up: ## Start the stack (Floci + services) in the background
	$(COMPOSE) up -d

down: ## Stop the stack
	$(COMPOSE) down

logs: ## Tail logs (optional: make logs S=users)
	$(COMPOSE) logs -f $(S)

build: ## Build service images
	$(COMPOSE) build

ps: ## Show container status
	$(COMPOSE) ps

## --- Terraform (against Floci) ---

infra-init: ## terraform init (environments/local)
	$(TF) init

infra-plan: ## terraform plan (environments/local)
	$(TF) plan

infra-up: ## terraform apply -auto-approve (environments/local), then refresh .env
	$(TF) apply -auto-approve
	$(MAKE) env-file

infra-down: ## terraform destroy -auto-approve (environments/local)
	$(TF) destroy -auto-approve

infra-output: ## Show terraform outputs (Cognito IDs, etc.)
	$(TF) output

env-file: ## Refresh Cognito IDs + API_GATEWAY_URL in ./.env from terraform outputs (preserves other vars)
	@# Floci mints a new user-pool/client ID (and api_id, and DB proxy IP) on every
	@# apply, so these must be rewritten from the live outputs — never hand-edited.
	@# docker-compose reads COGNITO_USER_POOL_ID / COGNITO_CLIENT_ID / API_GATEWAY_URL
	@# from here. USERS_DATABASE_URL is a HOST-reachable Postgres URL (Floci's DB
	@# proxy IP:<pgport>, routable from macOS/OrbStack) for inspecting the DB with a
	@# SQL client — distinct from the in-container DATABASE_WRITER_URL (floci:<pgport>).
	@# The RDS-proxy ports are DISCOVERED per-engine (pgport/myport) via
	@# discover-db-port.sh — Floci assigns them by creation order and they can flip
	@# across applies, so they are never hardcoded. We also write USERS_DB_PORT /
	@# ORDERS_DB_PORT so docker-compose (which cannot run commands) can interpolate them.
	@# The auto-generated lines are wrapped in a labeled box so it's clear
	@# what env-file owns. Only that box is regenerated; every line outside it
	@# (e.g. a manually-added APIDOG_ACCESS_TOKEN) is preserved. Box markers are
	@# `#` comments, which docker-compose ignores.
	@pool="$$($(TF) output -raw cognito_user_pool_id)"; \
	client="$$($(TF) output -raw cognito_client_id)"; \
	apiid="$$($(TF) output -raw api_id)"; \
	dbhost="$$($(TF) output -raw db_writer_endpoint)"; \
	ordersdbhost="$$($(TF) output -raw orders_db_writer_endpoint)"; \
	pgport="$$(bash $(DISCOVER_DB_PORT) postgres)"; \
	myport="$$(bash $(DISCOVER_DB_PORT) mysql)"; \
	touch $(ENV_FILE); \
	rest=$$(mktemp); \
	awk '/^# >>> AUTO-GENERATED/{skip=1;next} skip&&/^# <<< END AUTO-GENERATED/{skip=0;next} skip{next} {print}' $(ENV_FILE) \
		| grep -vE '^COGNITO_(USER_POOL_ID|CLIENT_ID)=' \
		| awk 'NF||p{print} {p=NF}' > $$rest; \
	out=$$(mktemp); \
	{ \
		printf '# >>> AUTO-GENERATED by `make env-file` (terraform outputs) — do not edit ─────\n'; \
		printf 'COGNITO_USER_POOL_ID=%s\n' "$$pool"; \
		printf 'COGNITO_CLIENT_ID=%s\n' "$$client"; \
		printf 'API_GATEWAY_URL=http://localhost:4566/restapis/%s/$$default/_user_request_\n' "$$apiid"; \
		printf 'USERS_DATABASE_URL=postgres://test:test@%s:%s/users\n' "$$dbhost" "$$pgport"; \
		printf 'ORDERS_DATABASE_URL=mysql://test:test@%s:%s/orders\n' "$$ordersdbhost" "$$myport"; \
		printf 'USERS_DB_PORT=%s\n' "$$pgport"; \
		printf 'ORDERS_DB_PORT=%s\n' "$$myport"; \
		printf '# <<< END AUTO-GENERATED ───────────────────────────────────────────────────\n'; \
		[ -s $$rest ] && printf '\n' && cat $$rest; \
	} > $$out; \
	mv $$out $(ENV_FILE); \
	rm -f $$rest
	@echo "refreshed the AUTO-GENERATED Cognito + API_GATEWAY_URL box in $(ENV_FILE) (other vars preserved)"

## --- Database migrations ---

migrate: ## Apply Prisma migrations (users) against Floci's Postgres (idempotent)
	@# `prisma migrate deploy` (never `migrate dev`: that one is interactive and
	@# can reset data — unsuitable for bootstrap). It must run as the cluster
	@# SUPERUSER (test/test), because migrations run DDL and users_app
	@# deliberately has none (ADR-0004: soft-delete enforced at grant level).
	@# It must ALSO be the same role bootstrap.sh's ALTER DEFAULT PRIVILEGES ran
	@# as, so users_app correctly inherits SELECT/INSERT/UPDATE on the tables
	@# this step creates — do not change to a different DB user.
	@#
	@# Runs inside the compose network via the `deps` build stage (the users
	@# Dockerfile already assembles it: workspace deps + prisma CLI + prisma/
	@# for @3mrai/users). We reuse that stage instead of publishing Floci's
	@# Postgres proxy port to the host — the port is Floci-internal and, per
	@# Floci's RDS proxy range (7000-7099) assigned by creation order, not
	@# guaranteed to stay 7001; staying in-network avoids depending on it as a
	@# host contract. Inside the compose network the host is `floci` and the port
	@# is the SAME proxy port describe-db-clusters reports, so we DISCOVER it
	@# per-engine (never hardcode 7001) and interpolate it into the URL.
	@# The users runtime image is production-only and has no prisma CLI/prisma/
	@# dir, so it cannot run this itself (see services/users/Dockerfile).
	docker build --target deps -t 3mrai-users:deps -f services/users/Dockerfile .
	@pgport="$$(bash $(DISCOVER_DB_PORT) postgres)"; \
	docker run --rm --network 3mrai_3mrai-network \
		-e DATABASE_WRITER_URL="postgres://test:test@floci:$$pgport/users" \
		-w /app/services/users \
		3mrai-users:deps \
		node node_modules/prisma/build/index.js migrate deploy --schema=./prisma/schema.prisma
	@echo "Prisma migrations applied."

infra-up-post: ## Phase 2: create DB app-users in Terraform (post-effects), after phase 1
	@# Two-phase apply (see docs/superpowers/specs/2026-07-15-two-phase-post-effects-design.md
	@# and environments/local/post/README.md): a SEPARATE Terraform root with its
	@# own state that reads phase-1 outputs + the master secret by ARN, waits for
	@# each DB via a healthcheck gate, and creates the least-privilege app-users
	@# (SELECT/INSERT/UPDATE, no DELETE — ADR-0004). Local enables postgres only
	@# (users_app); the mysql provider hangs on Floci so orders_app is prod-only.
	@# Runs host-side, reaching Floci's published RDS proxy ports (7000-7010).
	@# DISCOVER the Postgres proxy port per-engine and pass it as -var pg_port:
	@# Floci assigns those ports by creation order and they can flip across
	@# applies, so the variable's default (7001) is not reliable. (mysql is
	@# gated off locally; pass -var mysql_port=... too if it is ever enabled.)
	pgport="$$(bash $(DISCOVER_DB_PORT) postgres)"; \
	cd $(TF_LOCAL_DIR)/post && terraform init >/dev/null && terraform apply -auto-approve -var pg_port=$$pgport

## --- Orchestration ---

bootstrap: ## Bring the whole local chain up from scratch, in dependency order
	@# Order matters. The services cannot start before the infra exists: `users`
	@# validates COGNITO_* with Zod at boot, and those IDs only exist after apply.
	@# So: Floci first, then terraform, then .env, then migrations (DB needs
	@# tables before it's usable), then bootstrap.sh (app DB user + nginx
	@# alias), and only then the services.
	$(COMPOSE) up -d floci
	@echo "Waiting for Floci at $(FLOCI_URL) ..."
	@for i in $$(seq 1 30); do \
		if curl -sf -o /dev/null "$(FLOCI_URL)"; then echo "Floci is up."; break; fi; \
		if [ $$i -eq 30 ]; then echo "Floci did not become ready in time." >&2; exit 1; fi; \
		sleep 1; \
	done
	$(MAKE) infra-init
	$(MAKE) infra-up
	$(MAKE) migrate
	$(COMPOSE) up -d --build users
	bash $(TF_LOCAL_DIR)/bootstrap.sh
	@# Phase 2 (post-effects): create the least-privilege DB app-users in
	@# Terraform now that the clusters exist and migrations have run. Replaces the
	@# app-user step formerly in bootstrap.sh (which now only manages the nginx alias).
	$(MAKE) infra-up-post
	@# Orders migrates + seeds ITSELF on startup (SEED_ON_STARTUP=true in
	@# compose): the Api applies EF Core migrations then ProductSeed against
	@# Floci's MySQL before serving. This differs from Users (Prisma via `make
	@# migrate`) because no Aurora-MySQL cluster is provisioned in infra yet, so
	@# there is no standalone migrate target to run — the service owns its schema
	@# locally. Bring it up after users so the Users gRPC gate (users:50051) is
	@# reachable for POST /v1/orders.
	$(COMPOSE) up -d --build orders

clean: ## Tear down infra + compose (prompts before removing ./data)
	-$(TF) destroy -auto-approve
	$(COMPOSE) down
	@printf "Remove ./data (local emulator state)? [y/N] "; read ans; \
		if [ "$$ans" = "y" ] || [ "$$ans" = "Y" ]; then rm -rf ./data && echo "removed ./data"; else echo "kept ./data"; fi

observability-up: ## Start OpenObserve + the OTel collector (opt-in; ~512MB-1.5GB RAM)
	$(COMPOSE) --profile observability up -d
	@echo "OpenObserve UI on http://localhost:5080 once it's healthy (~5s)."
	@echo "Login: admin@3mrai.local / Complexpass#123"

observability-down: ## Stop the observability stack (leaves the rest running)
	$(COMPOSE) stop openobserve otel-collector
