load_module modules/ngx_http_js_module.so;
events {}
http {
  js_import auth from /etc/nginx/mounted/auth.js;
  js_set $jwt_sub auth.jwtSub;
  server {
    listen 80;
    location / {
      resolver 127.0.0.11 valid=5s;
      set $backend users;
      proxy_pass http://$backend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header x-user-id $jwt_sub;
    }
  }
}
