import { test, expect } from "@playwright/test";
import { getGatewayToken } from "../../support/auth.js";
import { gatewayClient } from "../../support/gateway-client.js";
import { openSocket, tryOpen } from "../../support/ws-client.js";

// Gateway E2E for the realtime WebSocket delivery of tracking status changes
// (docs/domains/events-pipeline realtime design). This is the only layer that
// exercises the WHOLE chain: gateway WS $connect -> authorizer (real Cognito
// JWT) -> connections table -> Orders -> Tracking TestMode progression -> SQS
// -> events-pipeline Lambda -> publishToUser (keyed by cognito_sub) -> the
// socket. Nothing here fakes the authorizer or the fan-out.
//
// WS_URL is generated by Task 9's Terraform apply into .env.local.debug, which
// playwright.config.ts loads alongside .env.local.infra / .env.local.users.
const WS_URL = process.env.WS_URL;

// Registers a user through the gateway (getGatewayToken — the established
// helper, see support/auth.ts) and returns both the token and a ready
// gatewayClient for placing orders. Does NOT write a second auth path.
async function newGatewayUser(): Promise<{
  token: string;
  api: Awaited<ReturnType<typeof gatewayClient>>;
}> {
  const { token } = await getGatewayToken();
  const api = await gatewayClient(token);
  return { token, api };
}

// Creates an order in TestMode (x-test-mode: true), which is what drives
// Tracking's four-step progression at ~10s intervals (~30s total) and is what
// makes Orders call Tracking's init-tracking in the first place — see
// tests/gateway/orders-flow.spec.ts for the full chain rationale. Tagged with
// X-E2E-Source via gatewayClient, so global-teardown's soft-delete sweep
// covers these rows the same as every other gateway spec.
async function createTestModeOrder(api: Awaited<ReturnType<typeof gatewayClient>>): Promise<string> {
  const products = await api.get("v1/products");
  expect(products.status(), `GET v1/products failed: ${await products.text()}`).toBe(200);
  const catalogue = await products.json();
  const product = catalogue.find((p: { unitsInStock: number }) => p.unitsInStock > 0);
  expect(product, "no product with stock in the catalogue").toBeTruthy();

  const created = await api.post("v1/orders", {
    headers: { "x-test-mode": "true" },
    data: { lines: [{ productId: product.id, quantity: 1 }] },
  });
  expect(created.status(), `order creation failed: ${await created.text()}`).toBe(201);
  const order = await created.json();
  expect(order.id).toMatch(/^ord_/);
  return order.id as string;
}

test.describe("realtime tracking events over websocket", () => {
  test.skip(!WS_URL, "WS_URL is not set — run `make bootstrap` (Task 9's realtime infra).");

  test("delivers all four status transitions to the owner", async () => {
    // TestMode progression is ~30s (four transitions at ~10s cadence), plus
    // headroom for SQS + Lambda per record. Not the whole suite's default 30s.
    test.setTimeout(90_000);

    const { token, api } = await newGatewayUser();
    const socket = await openSocket(WS_URL!, token);

    // x-test-mode drives the four-step progression — every transition emits,
    // DELIVERED included, with no suppression.
    const orderId = await createTestModeOrder(api);

    // 60s: the progression takes ~30s; the rest is headroom for SQS + Lambda,
    // matching the budget the internal tracking-flow spec already uses for the
    // slower email path. Bounded, not generous enough to make the suite crawl.
    await socket.waitForCount(4, 60_000);
    socket.close();

    // Assert the SET, not the sequence: the pipeline processes SQS records in
    // batches with no cross-record ordering guarantee (see the events-pipeline
    // CLAUDE.md — "partial batch responses"), so demanding strict order would
    // be flaky independent of whether the feature works.
    const statuses = (socket.messages as Array<{ status: string }>).map((m) => m.status).sort();
    expect(statuses).toEqual(["DELIVERED", "ON_THE_WAY", "OUT_FOR_DELIVERY", "SHIPPED"].sort());

    for (const message of socket.messages as Array<{ type: string; order_id: string }>) {
      expect(message.type).toBe("TRACKING_STATUS_CHANGED");
      expect(message.order_id).toBe(orderId);
    }
  });

  test("rejects an invalid token at the handshake", async () => {
    // Without this, a $connect that succeeded regardless of the token would
    // look identical to a working feature. This repo has a documented case
    // (docs/infrastructure/decisions/cognito-custom-auth-triggers.md) of the
    // emulator's native USER_AUTH/EMAIL_OTP flow returning tokens with NO
    // challenge at all, so a happy-path-only test here would have passed with
    // authentication entirely skipped. "not-a-real-jwt" cannot be
    // verified by any code path — it fails aws-jwt-verify's structural parsing
    // outright (functions/realtime-events/src/shared/jwt.ts), before
    // signature/claims are even checked — so this can only pass if the
    // authorizer's Deny path genuinely runs.
    expect(await tryOpen(WS_URL!, "not-a-real-jwt")).toBe(false);
  });

  test("does not deliver one user's events to another user", async () => {
    test.setTimeout(90_000);

    const alice = await newGatewayUser();
    const bob = await newGatewayUser();

    const aliceSocket = await openSocket(WS_URL!, alice.token);
    const bobSocket = await openSocket(WS_URL!, bob.token);

    const orderId = await createTestModeOrder(alice.api);

    await aliceSocket.waitForCount(4, 60_000);
    aliceSocket.close();
    bobSocket.close();

    // The only test that actually exercises the cognito_sub scoping
    // (publishToUser queries the connections GSI by author.cognito_sub — see
    // functions/events-pipeline/src/handlers/tracking-status-changed.ts). If
    // the pipeline pushed to every open connection instead of the owner's,
    // bob's socket would have received all four messages here too.
    expect(bobSocket.messages).toHaveLength(0);
    expect(
      (aliceSocket.messages as Array<{ order_id: string }>).every((m) => m.order_id === orderId),
    ).toBe(true);
  });
});
