// WHY: Render from the email catalog, not email-preview — preview lists four files
// but the catalog has eight entries (five tracking statuses share one component).
// WORKAROUND(local): Shell out to events-pipeline's tsx — e2e cannot import #email/*
// (no JSX transform, no package imports map). Use spawn (stderr preserved), not execFile.
// Do NOT pipe script via stdin to tsx — Node treats stdin as CJS and ESM import fails.
// Do NOT write script under os.tmpdir() — #email/* resolves from nearest package.json.
// See [[testing]]
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const pipelineDir = path.join(repoRoot, "functions", "events-pipeline");
const pipelineEnvPath = path.join(repoRoot, ".env.local.events-pipeline");

export interface RenderedTemplate {
  //: The CATALOG key (e.g. "tracking-status-changed-placed"), which is also the
  // screenshot filename. Deliberately the catalog key and not the source
  // filename — the whole point of this path is that five keys share one file.
  key: string;
  html: string;
}

// Inline render script — temp file under events-pipeline (see header WORKAROUND).
const RENDER_SCRIPT = `
import { catalog } from "#email/catalog";
import { renderTemplate } from "#email/renderer";

const rendered = [];
for (const [key, entry] of Object.entries(catalog)) {
  rendered.push({ key, html: await renderTemplate(key, entry.sampleProps) });
}
process.stdout.write(JSON.stringify(rendered));
`;

//: Why the dependency might be missing, phrased so a developer can act on it.
export class EmailCatalogUnavailableError extends Error {}

// CONTRACT: Cherry-pick `.env.local.events-pipeline` into the child only — global load
// leaks AWS_* / METRICS_ENABLED into every spec. Child needs DOCDB_*, SES_FROM_ADDRESS.
// See [[testing]]
function readPipelineEnv(): Record<string, string> {
  if (!fs.existsSync(pipelineEnvPath)) {
    // Same class as a missing `tsx`, and skipped for the same reason: the file
    // is GENERATED by `make env-file` from Terraform outputs, so its absence
    // means the local stack was never provisioned — a missing prerequisite, not
    // a broken template. Failing here would paint a red suite on a fresh
    // checkout for something no template change can fix.
    throw new EmailCatalogUnavailableError(
      `${pipelineEnvPath} does not exist, so the events-pipeline environment the email ` +
        "renderer validates at import time (DOCDB_*, SES_FROM_ADDRESS, ASSETS_BASE_URL) " +
        "cannot be supplied. Run `make env-file` from the repo root.",
    );
  }
  return dotenv.parse(fs.readFileSync(pipelineEnvPath, "utf8"));
}

/** Renders catalog or throws EmailCatalogUnavailableError (skip when workspace not installed). */
export async function renderCatalog(): Promise<RenderedTemplate[]> {
  // `tsx` is a devDependency of functions/events-pipeline. Its absence means the
  // workspace was never installed (or was installed with --prod), which is the
  // one condition this helper skips on.
  const tsxBin = path.join(pipelineDir, "node_modules", ".bin", "tsx");
  if (!fs.existsSync(tsxBin)) {
    throw new EmailCatalogUnavailableError(
      `tsx is not installed at ${tsxBin}, so the email catalog cannot be rendered. ` +
        "Run `nvm use && pnpm install` from the repo root.",
    );
  }

  // CONTRACT: NODE_OPTIONS must include --conditions=development or #email/* resolves to stale dist/.
  const pipelineEnv = readPipelineEnv();

  // WORKAROUND(local): mkdtemp under events-pipeline — os.tmpdir() breaks #email/* resolution.
  const scriptDir = await fsp.mkdtemp(path.join(pipelineDir, ".email-catalog-render-"));
  const scriptPath = path.join(scriptDir, "render-catalog.mts");

  let stdout: string;
  let stderr: string;
  let exitCode: number | null;
  try {
    await fsp.writeFile(scriptPath, RENDER_SCRIPT, "utf8");

    const child = spawn(tsxBin, [scriptPath], {
      cwd: pipelineDir,
      env: {
        ...pipelineEnv,
        ...process.env,
        NODE_OPTIONS: `${process.env.NODE_OPTIONS ?? ""} --conditions=development`.trim(),
      },
      stdio: ["ignore", "pipe", "pipe"],
    });

    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];
    child.stdout.on("data", (c: Buffer) => stdoutChunks.push(c));
    child.stderr.on("data", (c: Buffer) => stderrChunks.push(c));

    exitCode = await new Promise<number | null>((resolve, reject) => {
      child.once("error", reject);
      child.once("close", resolve);
    });

    stdout = Buffer.concat(stdoutChunks).toString("utf8");
    stderr = Buffer.concat(stderrChunks).toString("utf8");
  } finally {
    // The temp dir must not outlive the render, however it ended.
    await fsp.rm(scriptDir, { recursive: true, force: true });
  }

  if (exitCode !== 0) {
    // NOT an EmailCatalogUnavailableError: tsx exists and the render still
    // failed, which means the templates or the catalog are broken. That is a
    // real defect and must fail the spec rather than skip it.
    throw new Error(
      `Rendering the email catalog failed inside ${pipelineDir} (tsx exited ${exitCode}), ` +
        `running on Node ${process.version}. The renderer ran and threw, so this is not a ` +
        "missing dependency — read the stderr below before assuming the templates are at " +
        "fault: a module-resolution error usually means the toolchain, while a render or " +
        "validation error means the catalog.\n" +
        `${stderr.trim() || "(no stderr)"}`,
    );
  }

  const parsed = JSON.parse(stdout) as RenderedTemplate[];
  if (!Array.isArray(parsed) || parsed.length === 0) {
    throw new Error(
      "The catalog renderer produced no templates. src/email/catalog.ts exports an empty " +
        "object, which would also mean the pipeline can send no email at all.",
    );
  }
  return parsed;
}
