"""Generate env files with a regenerated AUTO-GENERATED box and a preserved CUSTOM one.

CONTRACT: Regeneration rewrites ONLY the machine half. Floci mints new Cognito
and api ids and reassigns DB proxy ports on every apply, while the CUSTOM box
holds hand-added values that must survive. See [[env-files]]
"""

import subprocess
from pathlib import Path

AUTO_BEGIN = "# >>> AUTO-GENERATED by `make env-file` — do not edit"
AUTO_END = "# <<< END AUTO-GENERATED"
CUSTOM_BEGIN = "# >>> CUSTOM — yours to edit; preserved across regeneration"
CUSTOM_END = "# <<< END CUSTOM"


class MissingValue(Exception):
    """A required value was absent. Raised with the key name, never silently skipped."""


def terraform_output(tf_dir: Path, name: str) -> str:
    """Read a single `terraform output -raw` value.

    Fails loudly: an empty or errored output would otherwise be written into a
    connection string as an empty segment, producing a service that starts and
    then cannot connect — far harder to diagnose than a failure here.
    """
    result = subprocess.run(
        ["terraform", f"-chdir={tf_dir}", "output", "-raw", name],
        capture_output=True,
        text=True,
    )
    value = result.stdout.strip()
    if result.returncode != 0 or not value:
        raise MissingValue(
            f"terraform output '{name}' is empty or failed "
            f"({result.stderr.strip() or 'no stderr'}). Has `make infra-up` run?"
        )
    return value


def read_custom_block(path: Path) -> list[str]:
    """The lines a human owns in an existing file, so regeneration can put them back.

    CONTRACT: For a file predating the CUSTOM markers, every line outside the
    AUTO box counts as custom — otherwise an existing hand-added value is
    silently dropped on the first regeneration. See [[env-files]]
    """
    if not path.exists():
        return []

    lines = path.read_text().splitlines()

    if any(line.startswith(CUSTOM_BEGIN) for line in lines):
        kept, inside = [], False
        for line in lines:
            if line.startswith(CUSTOM_BEGIN):
                inside = True
                continue
            if line.startswith(CUSTOM_END):
                inside = False
                continue
            if inside:
                kept.append(line)
        return _trimmed(kept)

    # Legacy shape: no CUSTOM markers yet. Everything outside AUTO is custom.
    kept, inside_auto = [], False
    for line in lines:
        if line.startswith("# >>> AUTO-GENERATED"):
            inside_auto = True
            continue
        if line.startswith("# <<< END AUTO-GENERATED"):
            inside_auto = False
            continue
        if not inside_auto:
            kept.append(line)
    return _trimmed(kept)


def _trimmed(lines: list[str]) -> list[str]:
    """Drop leading/trailing blank lines so boxes do not accumulate whitespace."""
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


def write_env_file(
    path: Path,
    *,
    header: str,
    generated: dict[str, str],
    custom_defaults: dict[str, str] | None = None,
) -> None:
    """Write `path` with a fresh AUTO box and the file's existing CUSTOM block.

    CONTRACT: Seed `custom_defaults` PER KEY, never all-or-nothing. Seeding only
    an empty box skips a newly added default for every checkout that already has
    a CUSTOM box, and the service boots without it. See [[env-files]]
    """
    for key, value in generated.items():
        if value is None or value == "":
            raise MissingValue(f"{path.name}: required value '{key}' is empty")

    existing_custom = read_custom_block(path)
    for key, value in (custom_defaults or {}).items():
        # A commented-out assignment counts as present: the developer
        # deliberately disabled it, and re-seeding would silently undo that.
        if not any(
            line.split("=", 1)[0].strip().lstrip("#").strip() == key
            for line in existing_custom
            if "=" in line
        ):
            existing_custom.append(f"{key}={value}")

    out: list[str] = [f"# {header}", AUTO_BEGIN]
    out += [f"{k}={v}" for k, v in generated.items()]
    out += [AUTO_END, "", CUSTOM_BEGIN]
    out += existing_custom
    out += [CUSTOM_END, ""]

    path.write_text("\n".join(out))
