# ─── Deployment package ──────────────────────────────────────────────────────────
# var.source_dir is the service's BUILT output (dist/). It must exist before a
# plan/apply — data sources are read at plan time, so a missing directory fails
# there, not at `terraform validate`. Build the function first.
data "archive_file" "this" {
  type        = "zip"
  source_dir  = var.source_dir
  output_path = "${path.module}/.build/${var.context.id}.zip"
}

# ─── IAM execution role ──────────────────────────────────────────────────────────
resource "aws_iam_role" "lambda_exec" {
  name = "${var.context.id}-lambda-exec"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })

  tags = merge(var.context.tags, { Name = "${var.context.id}-lambda-exec" })
}

# Least-privilege inline policy: consume from exactly one queue, send mail, log.
# `ses:*` and `logs:*` are scoped as tightly as those APIs allow — SES sending
# authorizes on the identity, which is not known to this module, and the log
# stream ARNs are generated by the service itself.
resource "aws_iam_role_policy" "lambda_exec" {
  name = "${var.context.id}-lambda-exec-policy"
  role = aws_iam_role.lambda_exec.id

  policy = jsonencode({
    Version = "2012-10-17"
    # `concat` with a 0-or-1 element list, not a statement carrying a
    # conditional Resource: an IAM statement with an empty Resource is invalid,
    # so the statement has to be absent rather than neutered when the consumer
    # does not fan out to WebSocket clients.
    # CONTRACT: SqsQuarantine is 0-or-1, never falling back to `queue_arn` —
    # SendMessage on the MAIN queue would let a rejected message be written back
    # onto the queue it just failed on. See [[events-pipeline-design]]
    Statement = concat(
      var.dlq_arn == "" ? [] : [
        {
          Sid    = "SqsQuarantine"
          Effect = "Allow"
          # SendMessage only: the consumer writes a rejected message to the DLQ
          # and never reads or deletes from it. Redrive is an operator action.
          Action   = ["sqs:SendMessage"]
          Resource = var.dlq_arn
        },
        ], [
        {
          Sid    = "SqsConsume"
          Effect = "Allow"
          Action = [
            "sqs:ReceiveMessage",
            "sqs:DeleteMessage",
            "sqs:GetQueueAttributes",
          ]
          Resource = var.queue_arn
        },
        {
          Sid      = "SesSend"
          Effect   = "Allow"
          Action   = ["ses:SendEmail", "ses:SendRawEmail"]
          Resource = "*"
        },
        {
          Sid    = "CloudWatchPutMetricData"
          Effect = "Allow"
          # Custom business metrics (emails_sent_total / emails_failed_total).
          #
          # `Resource = "*"` is the ONLY valid value here, not a shortcut taken for
          # convenience: PutMetricData supports no resource-level permissions at
          # all. Access is narrowed with the `cloudwatch:namespace` condition key
          # instead, which is what confines this function to our own namespace.
          Action   = ["cloudwatch:PutMetricData"]
          Resource = "*"
          Condition = {
            StringEquals = {
              "cloudwatch:namespace" = "3MRAI"
            }
          }
        },
        {
          # Scoped to THIS function's log group only. `logs:CreateLogGroup` is
          # deliberately absent: the group is created explicitly below, so the
          # runtime never needs to create it. The `:*` suffix covers the log
          # STREAMS within the group. Self-referential, so no account id or
          # region is hardcoded.
          Sid    = "Logs"
          Effect = "Allow"
          Action = [
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Resource = "${aws_cloudwatch_log_group.this.arn}:*"
        },
      ],
      # Read the connection registry and prune dead rows. Query needs the INDEX
      # ARN (the by-cognito-sub GSI), which is a distinct resource from the
      # table itself — granting only the table ARN makes the Query fail with
      # AccessDenied on the index, not on the table, which reads as a table
      # permission problem and is not.
      var.ws_connections_table_arn == "" ? [] : [{
        Sid      = "WsConnectionsRegistry"
        Effect   = "Allow"
        Action   = ["dynamodb:Query", "dynamodb:DeleteItem"]
        Resource = [var.ws_connections_table_arn, "${var.ws_connections_table_arn}/index/*"]
      }],
      # Push a frame to an open socket through the @connections management API.
      var.ws_manage_connections_arn == "" ? [] : [{
        Sid      = "WsManageConnections"
        Effect   = "Allow"
        Action   = ["execute-api:ManageConnections"]
        Resource = var.ws_manage_connections_arn
    }])
  })
}

# ─── Log group ────────────────────────────────────────────────────────────────────
# Declared explicitly (rather than left to Lambda's implicit creation) so
# retention is managed and the group is destroyed with the function. Its ARN is
# also what scopes the execution role's logs permissions above.
resource "aws_cloudwatch_log_group" "this" {
  name              = "/aws/lambda/${var.context.id}"
  retention_in_days = var.log_retention_in_days

  tags = merge(var.context.tags, { Name = "/aws/lambda/${var.context.id}" })
}

# ─── Lambda function ──────────────────────────────────────────────────────────────
resource "aws_lambda_function" "this" {
  function_name    = var.context.id
  role             = aws_iam_role.lambda_exec.arn
  handler          = var.handler
  runtime          = var.runtime
  filename         = data.archive_file.this.output_path
  source_code_hash = data.archive_file.this.output_base64sha256
  timeout          = var.timeout
  memory_size      = var.memory_size

  environment {
    # CONTRACT: This exact name and the STRING "true" — the SDK's emitter returns
    # early only on that pair. AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE is a
    # real variable for a DIFFERENT notice and suppresses nothing here;
    # `--no-deprecation` does not work either. Without it the SDK's node-version
    # warning goes to stderr, CloudWatch tags it ERROR, and it reaches
    # OpenObserve's `unclassified` stream once per cold start. Merged UNDER the
    # caller's variables so a consumer can still override it. Bumping to
    # nodejs22.x would also fix it, but provider 5.31.0 rejects that runtime.
    # See [[logging-context]]
    variables = merge(
      { AWS_SDK_JS_NODE_VERSION_SUPPORT_WARNING_DISABLED = "true" },
      var.environment_variables,
    )
  }

  tags = merge(var.context.tags, { Name = var.context.id })

  depends_on = [aws_cloudwatch_log_group.this]
}

# ─── SQS event source mapping ──────────────────────────────────────────────────────
# WORKAROUND(local): function_response_types MUST be set at CREATE time. Floci
# silently drops FunctionResponseTypes on `update-event-source-mapping` — the
# call returns success, the field comes back `[]`, partial batch responses stop
# being honored, and one failed record retries the whole batch. Adding it to an
# EXISTING mapping means RECREATING it (`-replace`), never an in-place update.
# WORKAROUND(local): mapping_count is the concurrency knob because Floci keeps
# one invocation in flight per mapping and ignores ScalingConfig. Leave it at 1
# in deployed environments — real Lambda scales one mapping out itself. Extra
# pollers add readers, not copies: SQS hands each message to one receiver.
# See [[floci-sqs-lambda-docdb-support]]
resource "aws_lambda_event_source_mapping" "sqs_trigger" {
  count                   = var.mapping_count
  event_source_arn        = var.queue_arn
  function_name           = aws_lambda_function.this.arn
  batch_size              = var.batch_size
  function_response_types = ["ReportBatchItemFailures"]
}

# ─── Function URL (optional) ──────────────────────────────────────────────────
# WARNING: authorization_type NONE is acceptable only because the handler
# authenticates every request itself — 404 unless E2E_TESTING_ENABLED and a
# constant-time match on x-e2e-token. The token is the boundary, not the URL.
# CONTRACT: Do NOT "harden" this to AWS_IAM. The Playwright suite reaches these
# URLs with a plain fetch and holds no SigV4 signer, so the switch breaks the
# only consumer and leaves the token check untouched. See [[testing]]
resource "aws_lambda_function_url" "this" {
  count              = var.enable_function_url ? 1 : 0
  function_name      = aws_lambda_function.this.function_name
  authorization_type = "NONE"
}
