# ─── Deployment package ──────────────────────────────────────────────────────────
# var.source_dir is the service's BUILT output (dist/). It must exist before a
# plan/apply — data sources are read at plan time, so a missing directory fails
# there, not at `terraform validate`. Build the function first.
data "archive_file" "this" {
  type        = "zip"
  source_dir  = var.source_dir
  output_path = "${path.module}/.build/${var.context.id}.zip"
}

# ─── IAM execution role ──────────────────────────────────────────────────────────
resource "aws_iam_role" "lambda_exec" {
  name = "${var.context.id}-lambda-exec"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })

  tags = merge(var.context.tags, { Name = "${var.context.id}-lambda-exec" })
}

# Least-privilege inline policy: consume from exactly one queue, send mail, log.
# `ses:*` and `logs:*` are scoped as tightly as those APIs allow — SES sending
# authorizes on the identity, which is not known to this module, and the log
# stream ARNs are generated by the service itself.
resource "aws_iam_role_policy" "lambda_exec" {
  name = "${var.context.id}-lambda-exec-policy"
  role = aws_iam_role.lambda_exec.id

  policy = jsonencode({
    Version = "2012-10-17"
    # `concat` with a 0-or-1 element list, not a statement carrying a
    # conditional Resource: an IAM statement with an empty Resource is invalid,
    # so the statement has to be absent rather than neutered when the consumer
    # does not fan out to WebSocket clients.
    Statement = concat([
      {
        Sid    = "SqsConsume"
        Effect = "Allow"
        Action = [
          "sqs:ReceiveMessage",
          "sqs:DeleteMessage",
          "sqs:GetQueueAttributes",
        ]
        Resource = var.queue_arn
      },
      {
        Sid      = "SesSend"
        Effect   = "Allow"
        Action   = ["ses:SendEmail", "ses:SendRawEmail"]
        Resource = "*"
      },
      {
        Sid    = "CloudWatchPutMetricData"
        Effect = "Allow"
        # Custom business metrics (emails_sent_total / emails_failed_total).
        #
        # `Resource = "*"` is the ONLY valid value here, not a shortcut taken for
        # convenience: PutMetricData supports no resource-level permissions at
        # all. Access is narrowed with the `cloudwatch:namespace` condition key
        # instead, which is what confines this function to our own namespace.
        Action   = ["cloudwatch:PutMetricData"]
        Resource = "*"
        Condition = {
          StringEquals = {
            "cloudwatch:namespace" = "3MRAI"
          }
        }
      },
      {
        # Scoped to THIS function's log group only. `logs:CreateLogGroup` is
        # deliberately absent: the group is created explicitly below, so the
        # runtime never needs to create it. The `:*` suffix covers the log
        # STREAMS within the group. Self-referential, so no account id or
        # region is hardcoded.
        Sid    = "Logs"
        Effect = "Allow"
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Resource = "${aws_cloudwatch_log_group.this.arn}:*"
      },
      ],
      # Read the connection registry and prune dead rows. Query needs the INDEX
      # ARN (the by-cognito-sub GSI), which is a distinct resource from the
      # table itself — granting only the table ARN makes the Query fail with
      # AccessDenied on the index, not on the table, which reads as a table
      # permission problem and is not.
      var.ws_connections_table_arn == "" ? [] : [{
        Sid      = "WsConnectionsRegistry"
        Effect   = "Allow"
        Action   = ["dynamodb:Query", "dynamodb:DeleteItem"]
        Resource = [var.ws_connections_table_arn, "${var.ws_connections_table_arn}/index/*"]
      }],
      # Push a frame to an open socket through the @connections management API.
      var.ws_manage_connections_arn == "" ? [] : [{
        Sid      = "WsManageConnections"
        Effect   = "Allow"
        Action   = ["execute-api:ManageConnections"]
        Resource = var.ws_manage_connections_arn
    }])
  })
}

# ─── Log group ────────────────────────────────────────────────────────────────────
# Declared explicitly (rather than left to Lambda's implicit creation) so
# retention is managed and the group is destroyed with the function. Its ARN is
# also what scopes the execution role's logs permissions above.
resource "aws_cloudwatch_log_group" "this" {
  name              = "/aws/lambda/${var.context.id}"
  retention_in_days = var.log_retention_in_days

  tags = merge(var.context.tags, { Name = "/aws/lambda/${var.context.id}" })
}

# ─── Lambda function ──────────────────────────────────────────────────────────────
resource "aws_lambda_function" "this" {
  function_name    = var.context.id
  role             = aws_iam_role.lambda_exec.arn
  handler          = var.handler
  runtime          = var.runtime
  filename         = data.archive_file.this.output_path
  source_code_hash = data.archive_file.this.output_base64sha256
  timeout          = var.timeout
  memory_size      = var.memory_size

  environment {
    # Silence the AWS SDK v3 maintenance notice at the SOURCE, merged UNDER the
    # caller's variables so a consumer can still override it explicitly.
    #
    # The SDK warns that releases after early 2027 will require node >= 22, and
    # emits it through process.emitWarning — which the Lambda runtime writes to
    # stderr, and CloudWatch tags every stderr line ERROR. So a purely
    # informational notice reaches OpenObserve at the same severity as a real
    # failure, once per cold start, carrying no service_name and severity 0. It
    # therefore lands in the `unclassified` stream and fails
    # e2e/tests/observability/unclassified-logs.spec.ts, which is right to
    # demand the PRODUCER be fixed.
    #
    # THE NAME AND THE VALUE BOTH MATTER. The emitter is the authority:
    # @aws-sdk/core/dist-es/submodules/client/emitWarningIfUnsupportedVersion.js
    # returns early only on
    # `AWS_SDK_JS_NODE_VERSION_SUPPORT_WARNING_DISABLED === "true"` — the STRING
    # "true", not "1". The similarly-named
    # AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE is a real AWS variable for a
    # DIFFERENT message (the SDK v2 maintenance notice), so setting it is
    # accepted silently and suppresses nothing — measured: it reached the
    # deployed functions and the warning kept flowing. `--no-deprecation` does
    # not work either; the notice is not a DeprecationWarning.
    #
    # The same fix sits on the WebSocket functions in
    # modules/api-gateway-ws/main.tf; this extends it to every consumer of this
    # module, which is where the loudest producer (the events pipeline) lives.
    #
    # Bumping the runtime to nodejs22.x would ALSO fix it and is the real
    # migration, but it is blocked here: the AWS provider is pinned to = 5.31.0
    # (see infra/CLAUDE.md), whose runtime validation tops out at nodejs20.x and
    # rejects nodejs22.x at plan time. Verified by trying it.
    variables = merge(
      { AWS_SDK_JS_NODE_VERSION_SUPPORT_WARNING_DISABLED = "true" },
      var.environment_variables,
    )
  }

  tags = merge(var.context.tags, { Name = var.context.id })

  depends_on = [aws_cloudwatch_log_group.this]
}

# ─── SQS event source mapping ──────────────────────────────────────────────────────
# `function_response_types = ["ReportBatchItemFailures"]` MUST be set here, at
# CREATE time. Floci silently drops FunctionResponseTypes on
# `update-event-source-mapping` — the call returns success and the field comes
# back as `[]` — while `create-event-source-mapping` persists it correctly
# (verified 2026-08-03 against Floci v1.5.28; see
# docs/lessons/floci-sqs-lambda-docdb-support.md, Finding 3).
#
# Consequence: if this field is ever added to an ALREADY-EXISTING mapping,
# RECREATE the mapping (`terraform taint` / `-replace`) instead of letting
# Terraform update it in place. An in-place update LOOKS like it worked and
# silently stops partial batch responses from being honored, so every single
# failed record retries the entire batch. Verify with:
#   aws lambda get-event-source-mapping --uuid <uuid> --query FunctionResponseTypes
# and expect ["ReportBatchItemFailures"].
# `count`, and it is a LOCAL-EMULATOR concession that costs production nothing.
#
# Real Lambda scales one mapping out to many concurrent invocations on its own,
# so `mapping_count = 1` (the default, and what every deployed environment uses)
# is correct there and a second mapping would only duplicate polling.
#
# Floci does not scale that way. Measured on this stack: it keeps ONE invocation
# in flight PER MAPPING, and the next poll starts about a second after the
# previous batch ENDS — so throughput is batch_size / (handler_duration + ~1s),
# which is also why a larger batch_size measured WORSE (one slow batch delays
# the next poll). `ScalingConfig.MaximumConcurrency` is stored by the API and
# then ignored.
#
# Each mapping does get its own independent poller, and they overlap. Same
# stack, same 80 events, only this variable changed:
#
#   mapping_count = 1  ->  79s, 1.02 ev/s
#   mapping_count = 4  ->  24s, 3.37 ev/s
#
# Verified safe rather than assumed: the four pollers split the work (20/20/20/80
# records across four containers), with zero failures, zero duplicate-event
# errors against the unique index on event_id, and an empty DLQ. SQS hands each
# message to exactly one receiver, so extra pollers add readers, not copies.
resource "aws_lambda_event_source_mapping" "sqs_trigger" {
  count                   = var.mapping_count
  event_source_arn        = var.queue_arn
  function_name           = aws_lambda_function.this.arn
  batch_size              = var.batch_size
  function_response_types = ["ReportBatchItemFailures"]
}

# ─── Function URL (optional) ──────────────────────────────────────────────────
# Count-gated so no environment gets a public URL unless it asks for one.
#
# `authorization_type = "NONE"` is acceptable HERE, and only here, because the
# handler authenticates every request itself: it answers 404 unless
# E2E_TESTING_ENABLED is true AND E2E_QUERY_TOKEN is set AND the request presents
# that token in `x-e2e-token`, compared in constant time (see
# functions/events-pipeline/src/e2e/http-query.ts). The URL is not the security
# boundary; the token is.
#
# Do NOT "harden" this to AWS_IAM. Floci's Function URLs are reached by a plain
# fetch from the Playwright suite, which holds no SigV4 signer, so switching the
# auth type does not tighten the route — it breaks the only consumer while
# leaving the token check that actually guards it untouched.
resource "aws_lambda_function_url" "this" {
  count              = var.enable_function_url ? 1 : 0
  function_name      = aws_lambda_function.this.function_name
  authorization_type = "NONE"
}
