// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysql

import (
	"database/sql"
	"encoding/json"
	"time"

	tagtype "github.com/jemartinez/3mrai/services/tracking-go/internal/adapter/mysql/tagtype"
)

type Tracking struct {
	ID              string
	UserID          string
	OrderID         string
	Status          string
	ShippingAddress json.RawMessage
	Datetime        time.Time
	CreatedBy       sql.NullString
	CreatedAt       time.Time
	UpdatedBy       sql.NullString
	UpdatedAt       time.Time
	DeletedBy       sql.NullString
	DeletedAt       sql.NullTime
	CognitoSub      sql.NullString
	Tags            tagtype.Tags
	TrackingNumber  string
}

type TrackingHistory struct {
	TrackingID string
	Status     string
	UserID     string
	OrderID    string
	Datetime   time.Time
	CreatedBy  sql.NullString
	CreatedAt  time.Time
	UpdatedBy  sql.NullString
	UpdatedAt  time.Time
	DeletedBy  sql.NullString
	DeletedAt  sql.NullTime
	CognitoSub sql.NullString
}
