// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysql

import (
	"context"
	"database/sql"
	"encoding/json"
)

type Querier interface {
	// The ONLY path that brings a tracking into existence.
	//
	// `datetime` and the audit timestamps are all passed in from ONE minted `now`,
	// never from several time.Now() calls: MySQL DATETIME here has fsp 0 and ROUNDS
	// fractional seconds rather than truncating, so two calls a millisecond apart
	// can land on different seconds.
	CreateTracking(ctx context.Context, arg CreateTrackingParams) error
	// One row per transition. The composite PK (tracking_id, status) makes a
	// duplicate transition fail at INSERT — a second enforcement of the forward-only
	// state machine, independent of the application guard.
	//
	// No id, no tags, no shipping_address: all three omissions are deliberate.
	CreateTrackingHistory(ctx context.Context, arg CreateTrackingHistoryParams) error
	// Queries for the tracking and tracking_history tables.
	//
	// TWO RULES THAT APPLY TO EVERY QUERY IN THIS FILE:
	//
	// 1. `datetime` is BACKTICKED and ALIASED. It is also a MySQL type keyword, so
	//    an unbackticked reference is a syntax error reported at an unhelpful
	//    location. Every SELECT aliases it to occurred_at so the generated Go field
	//    is a legal, readable identifier.
	//
	// 2. sqlc.slice() GENERATES INVALID SQL FOR AN EMPTY SLICE. sqlc expands the
	//    placeholder once per element, so zero elements produces `IN ()`, which
	//    MySQL rejects outright. Every caller of a query using sqlc.slice MUST
	//    short-circuit to an empty result WITHOUT querying when the slice is empty.
	//    The Python does exactly this. See ListTrackingsByIDs below.
	//
	// Soft delete: every read filters `deleted_at IS NULL`. The application never
	// issues DELETE, and the database user has no DELETE grant.
	// UNSCOPED lookup, used by the internal/gRPC path. Deliberately a SEPARATE query
	// from the scoped one below rather than one query with an optional parameter:
	// Go's zero value for string is "", not nil, so an optional-parameter port
	// silently converts "unscoped" into "scoped to the empty string".
	GetTrackingByOrderID(ctx context.Context, orderID string) (GetTrackingByOrderIDRow, error)
	// OWNERSHIP-SCOPED lookup for the user-facing REST reads.
	//
	// Scoped by cognito_sub, NEVER by user_id. The gateway injects the JWT `sub` as
	// the x-user-id header; user_id holds the internal usr_ id Orders resolved
	// through Users. Comparing a sub against a usr_ id never matches, so scoping by
	// user_id would answer 404 for every read — including the caller's own tracking —
	// while looking perfectly implemented.
	GetTrackingByOrderIDScoped(ctx context.Context, arg GetTrackingByOrderIDScopedParams) (GetTrackingByOrderIDScopedRow, error)
	// The e2e-cleanup selector. JSON_CONTAINS is how a MySQL JSON array is queried
	// for membership (verified against MySQL 8.0.46).
	//
	// The tag argument must be the EXACT literal "E2E Source" — space, capitals and
	// all. Users' teardown selects on the same string; a near-miss would clean up
	// nothing while looking correct.
	ListE2ETrackingIDs(ctx context.Context, dollar_1 json.RawMessage) ([]string, error)
	// History for one tracking.
	//
	// ORDER BY datetime alone is NOT deterministic: DATETIME has fsp 0 (second
	// resolution) and one unit of work stamps every row it writes from a single
	// `now`, so ties are common. On a tie MySQL is free to return primary-key order,
	// which for (tracking_id, status) is ALPHABETICAL — DELIVERED first. The FIELD()
	// tiebreaker maps each status to its progression position; domain.SortHistory
	// applies the same rule in Go for any path that assembles history in memory.
	ListTrackingHistory(ctx context.Context, trackingID string) ([]ListTrackingHistoryRow, error)
	// The caller's own trackings. Scoped by cognito_sub for the reason above.
	ListTrackingsByCognitoSub(ctx context.Context, cognitoSub sql.NullString) ([]ListTrackingsByCognitoSubRow, error)
	// Batch fetch by primary key.
	//
	// !! THE CALLER MUST SHORT-CIRCUIT ON AN EMPTY ids SLICE !!
	// sqlc expands sqlc.slice('ids') once per element. With zero elements the
	// generated SQL is `IN ()`, which MySQL rejects with a syntax error. Return an
	// empty result WITHOUT calling this query when len(ids) == 0.
	ListTrackingsByIDs(ctx context.Context, ids []string) ([]ListTrackingsByIDsRow, error)
	// History side of the account-deletion cascade.
	SoftDeleteTrackingHistoryByCognitoSub(ctx context.Context, arg SoftDeleteTrackingHistoryByCognitoSubParams) (int64, error)
	// Account-deletion cascade. Soft delete only: stamps deleted_at/deleted_by and
	// never issues DELETE.
	SoftDeleteTrackingsByCognitoSub(ctx context.Context, arg SoftDeleteTrackingsByCognitoSubParams) (int64, error)
	// Advance a tracking's status. Returns the affected-row count so the caller can
	// distinguish "updated" from "no such live tracking" without a second read.
	UpdateTrackingStatus(ctx context.Context, arg UpdateTrackingStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
