// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package mysql

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"

	tagtype "github.com/jemartinez/3mrai/services/tracking-go/internal/adapter/mysql/tagtype"
)

const createTracking = `-- name: CreateTracking :exec
INSERT INTO tracking (
  id,
  user_id,
  order_id,
  status,
  shipping_address,
  ` + "`" + `datetime` + "`" + `,
  created_by,
  created_at,
  updated_by,
  updated_at,
  cognito_sub,
  tags,
  tracking_number
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTrackingParams struct {
	ID              string
	UserID          string
	OrderID         string
	Status          string
	ShippingAddress []byte
	Datetime        time.Time
	CreatedBy       sql.NullString
	CreatedAt       time.Time
	UpdatedBy       sql.NullString
	UpdatedAt       time.Time
	CognitoSub      sql.NullString
	Tags            tagtype.Tags
	TrackingNumber  string
}

// The ONLY path that brings a tracking into existence.
//
// `datetime` and the audit timestamps are all passed in from ONE minted `now`,
// never from several time.Now() calls: MySQL DATETIME here has fsp 0 and ROUNDS
// fractional seconds rather than truncating, so two calls a millisecond apart
// can land on different seconds.
func (q *Queries) CreateTracking(ctx context.Context, arg CreateTrackingParams) error {
	_, err := q.db.ExecContext(ctx, createTracking,
		arg.ID,
		arg.UserID,
		arg.OrderID,
		arg.Status,
		arg.ShippingAddress,
		arg.Datetime,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.CognitoSub,
		arg.Tags,
		arg.TrackingNumber,
	)
	return err
}

const createTrackingHistory = `-- name: CreateTrackingHistory :exec
INSERT INTO tracking_history (
  tracking_id,
  status,
  user_id,
  order_id,
  ` + "`" + `datetime` + "`" + `,
  created_by,
  created_at,
  updated_by,
  updated_at,
  cognito_sub
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTrackingHistoryParams struct {
	TrackingID string
	Status     string
	UserID     string
	OrderID    string
	Datetime   time.Time
	CreatedBy  sql.NullString
	CreatedAt  time.Time
	UpdatedBy  sql.NullString
	UpdatedAt  time.Time
	CognitoSub sql.NullString
}

// One row per transition. The composite PK (tracking_id, status) makes a
// duplicate transition fail at INSERT — a second enforcement of the forward-only
// state machine, independent of the application guard.
//
// No id, no tags, no shipping_address: all three omissions are deliberate.
func (q *Queries) CreateTrackingHistory(ctx context.Context, arg CreateTrackingHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createTrackingHistory,
		arg.TrackingID,
		arg.Status,
		arg.UserID,
		arg.OrderID,
		arg.Datetime,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.CognitoSub,
	)
	return err
}

const getTrackingByOrderID = `-- name: GetTrackingByOrderID :one

SELECT
  id,
  user_id,
  order_id,
  status,
  shipping_address,
  ` + "`" + `datetime` + "`" + ` AS occurred_at,
  created_by,
  created_at,
  updated_by,
  updated_at,
  deleted_by,
  deleted_at,
  cognito_sub,
  tags,
  tracking_number
FROM tracking
WHERE order_id = ?
  AND deleted_at IS NULL
`

type GetTrackingByOrderIDRow struct {
	ID              string
	UserID          string
	OrderID         string
	Status          string
	ShippingAddress []byte
	OccurredAt      time.Time
	CreatedBy       sql.NullString
	CreatedAt       time.Time
	UpdatedBy       sql.NullString
	UpdatedAt       time.Time
	DeletedBy       sql.NullString
	DeletedAt       sql.NullTime
	CognitoSub      sql.NullString
	Tags            tagtype.Tags
	TrackingNumber  string
}

// Queries for the tracking and tracking_history tables.
//
// TWO RULES THAT APPLY TO EVERY QUERY IN THIS FILE:
//
//  1. `datetime` is BACKTICKED and ALIASED. It is also a MySQL type keyword, so
//     an unbackticked reference is a syntax error reported at an unhelpful
//     location. Every SELECT aliases it to occurred_at so the generated Go field
//     is a legal, readable identifier.
//
//  2. sqlc.slice() GENERATES INVALID SQL FOR AN EMPTY SLICE. sqlc expands the
//     placeholder once per element, so zero elements produces `IN ()`, which
//     MySQL rejects outright. Every caller of a query using sqlc.slice MUST
//     short-circuit to an empty result WITHOUT querying when the slice is empty.
//     The Python does exactly this. See ListTrackingsByIDs below.
//
// Soft delete: every read filters `deleted_at IS NULL`. The application never
// issues DELETE, and the database user has no DELETE grant.
// UNSCOPED lookup, used by the internal/gRPC path. Deliberately a SEPARATE query
// from the scoped one below rather than one query with an optional parameter:
// Go's zero value for string is "", not nil, so an optional-parameter port
// silently converts "unscoped" into "scoped to the empty string".
func (q *Queries) GetTrackingByOrderID(ctx context.Context, orderID string) (GetTrackingByOrderIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackingByOrderID, orderID)
	var i GetTrackingByOrderIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.Status,
		&i.ShippingAddress,
		&i.OccurredAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CognitoSub,
		&i.Tags,
		&i.TrackingNumber,
	)
	return i, err
}

const getTrackingByOrderIDScoped = `-- name: GetTrackingByOrderIDScoped :one
SELECT
  id,
  user_id,
  order_id,
  status,
  shipping_address,
  ` + "`" + `datetime` + "`" + ` AS occurred_at,
  created_by,
  created_at,
  updated_by,
  updated_at,
  deleted_by,
  deleted_at,
  cognito_sub,
  tags,
  tracking_number
FROM tracking
WHERE order_id = ?
  AND cognito_sub = ?
  AND deleted_at IS NULL
`

type GetTrackingByOrderIDScopedParams struct {
	OrderID    string
	CognitoSub sql.NullString
}

type GetTrackingByOrderIDScopedRow struct {
	ID              string
	UserID          string
	OrderID         string
	Status          string
	ShippingAddress []byte
	OccurredAt      time.Time
	CreatedBy       sql.NullString
	CreatedAt       time.Time
	UpdatedBy       sql.NullString
	UpdatedAt       time.Time
	DeletedBy       sql.NullString
	DeletedAt       sql.NullTime
	CognitoSub      sql.NullString
	Tags            tagtype.Tags
	TrackingNumber  string
}

// OWNERSHIP-SCOPED lookup for the user-facing REST reads.
//
// Scoped by cognito_sub, NEVER by user_id. The gateway injects the JWT `sub` as
// the x-user-id header; user_id holds the internal usr_ id Orders resolved
// through Users. Comparing a sub against a usr_ id never matches, so scoping by
// user_id would answer 404 for every read — including the caller's own tracking —
// while looking perfectly implemented.
func (q *Queries) GetTrackingByOrderIDScoped(ctx context.Context, arg GetTrackingByOrderIDScopedParams) (GetTrackingByOrderIDScopedRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackingByOrderIDScoped, arg.OrderID, arg.CognitoSub)
	var i GetTrackingByOrderIDScopedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.Status,
		&i.ShippingAddress,
		&i.OccurredAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CognitoSub,
		&i.Tags,
		&i.TrackingNumber,
	)
	return i, err
}

const listE2ETrackingIDs = `-- name: ListE2ETrackingIDs :many
SELECT id
FROM tracking
WHERE JSON_CONTAINS(tags, CAST(? AS JSON))
  AND deleted_at IS NULL
`

// DO NOT USE. Superseded by internal/adapter/mysql/soft_delete.go, which uses
// JSON_CONTAINS(tags, JSON_QUOTE(?)) -- the membership test verified against
// MySQL 8.0.46. CAST(? AS JSON) is not the same predicate.
// The e2e-cleanup selector. JSON_CONTAINS is how a MySQL JSON array is queried
// for membership (verified against MySQL 8.0.46).
//
// The tag argument must be the EXACT literal "E2E Source" — space, capitals and
// all. Users' teardown selects on the same string; a near-miss would clean up
// nothing while looking correct.
func (q *Queries) ListE2ETrackingIDs(ctx context.Context, dollar_1 json.RawMessage) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listE2ETrackingIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingHistory = `-- name: ListTrackingHistory :many
SELECT
  tracking_id,
  status,
  user_id,
  order_id,
  ` + "`" + `datetime` + "`" + ` AS occurred_at,
  created_by,
  created_at,
  updated_by,
  updated_at,
  deleted_by,
  deleted_at,
  cognito_sub
FROM tracking_history
WHERE tracking_id = ?
  AND deleted_at IS NULL
ORDER BY
  ` + "`" + `datetime` + "`" + ` ASC,
  FIELD(status, 'PLACED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED') ASC
`

type ListTrackingHistoryRow struct {
	TrackingID string
	Status     string
	UserID     string
	OrderID    string
	OccurredAt time.Time
	CreatedBy  sql.NullString
	CreatedAt  time.Time
	UpdatedBy  sql.NullString
	UpdatedAt  time.Time
	DeletedBy  sql.NullString
	DeletedAt  sql.NullTime
	CognitoSub sql.NullString
}

// History for one tracking.
//
// ORDER BY datetime alone is NOT deterministic: DATETIME has fsp 0 (second
// resolution) and one unit of work stamps every row it writes from a single
// `now`, so ties are common. On a tie MySQL is free to return primary-key order,
// which for (tracking_id, status) is ALPHABETICAL — DELIVERED first. The FIELD()
// tiebreaker maps each status to its progression position; domain.SortHistory
// applies the same rule in Go for any path that assembles history in memory.
func (q *Queries) ListTrackingHistory(ctx context.Context, trackingID string) ([]ListTrackingHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackingHistory, trackingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackingHistoryRow{}
	for rows.Next() {
		var i ListTrackingHistoryRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.Status,
			&i.UserID,
			&i.OrderID,
			&i.OccurredAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.CognitoSub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingsByCognitoSub = `-- name: ListTrackingsByCognitoSub :many
SELECT
  id,
  user_id,
  order_id,
  status,
  shipping_address,
  ` + "`" + `datetime` + "`" + ` AS occurred_at,
  created_by,
  created_at,
  updated_by,
  updated_at,
  deleted_by,
  deleted_at,
  cognito_sub,
  tags,
  tracking_number
FROM tracking
WHERE cognito_sub = ?
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListTrackingsByCognitoSubRow struct {
	ID              string
	UserID          string
	OrderID         string
	Status          string
	ShippingAddress []byte
	OccurredAt      time.Time
	CreatedBy       sql.NullString
	CreatedAt       time.Time
	UpdatedBy       sql.NullString
	UpdatedAt       time.Time
	DeletedBy       sql.NullString
	DeletedAt       sql.NullTime
	CognitoSub      sql.NullString
	Tags            tagtype.Tags
	TrackingNumber  string
}

// The caller's own trackings. Scoped by cognito_sub for the reason above.
func (q *Queries) ListTrackingsByCognitoSub(ctx context.Context, cognitoSub sql.NullString) ([]ListTrackingsByCognitoSubRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackingsByCognitoSub, cognitoSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackingsByCognitoSubRow{}
	for rows.Next() {
		var i ListTrackingsByCognitoSubRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderID,
			&i.Status,
			&i.ShippingAddress,
			&i.OccurredAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.CognitoSub,
			&i.Tags,
			&i.TrackingNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingsByIDs = `-- name: ListTrackingsByIDs :many
SELECT
  id,
  user_id,
  order_id,
  status,
  shipping_address,
  ` + "`" + `datetime` + "`" + ` AS occurred_at,
  created_by,
  created_at,
  updated_by,
  updated_at,
  deleted_by,
  deleted_at,
  cognito_sub,
  tags,
  tracking_number
FROM tracking
WHERE id IN (/*SLICE:ids*/?)
  AND deleted_at IS NULL
`

type ListTrackingsByIDsRow struct {
	ID              string
	UserID          string
	OrderID         string
	Status          string
	ShippingAddress []byte
	OccurredAt      time.Time
	CreatedBy       sql.NullString
	CreatedAt       time.Time
	UpdatedBy       sql.NullString
	UpdatedAt       time.Time
	DeletedBy       sql.NullString
	DeletedAt       sql.NullTime
	CognitoSub      sql.NullString
	Tags            tagtype.Tags
	TrackingNumber  string
}

// Batch fetch by primary key.
//
// !! THE CALLER MUST SHORT-CIRCUIT ON AN EMPTY ids SLICE !!
// sqlc expands sqlc.slice('ids') once per element. With zero elements the
// generated SQL is `IN ()`, which MySQL rejects with a syntax error. Return an
// empty result WITHOUT calling this query when len(ids) == 0.
func (q *Queries) ListTrackingsByIDs(ctx context.Context, ids []string) ([]ListTrackingsByIDsRow, error) {
	query := listTrackingsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackingsByIDsRow{}
	for rows.Next() {
		var i ListTrackingsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderID,
			&i.Status,
			&i.ShippingAddress,
			&i.OccurredAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.CognitoSub,
			&i.Tags,
			&i.TrackingNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrackingHistoryByCognitoSub = `-- name: SoftDeleteTrackingHistoryByCognitoSub :execrows
UPDATE tracking_history
SET deleted_at = ?,
    deleted_by = ?
WHERE cognito_sub = ?
  AND deleted_at IS NULL
`

type SoftDeleteTrackingHistoryByCognitoSubParams struct {
	DeletedAt  sql.NullTime
	DeletedBy  sql.NullString
	CognitoSub sql.NullString
}

// DO NOT USE. Superseded by internal/adapter/mysql/soft_delete.go. Besides the
// two defects above, this one filters history by its OWN cognito_sub column
// rather than by the parent's id through the FK, so history hanging off a row
// with a NULL sub is never swept -- leaving live children under a deleted
// parent, which is exactly what the children-first ordering exists to prevent.
// History side of the account-deletion cascade.
func (q *Queries) SoftDeleteTrackingHistoryByCognitoSub(ctx context.Context, arg SoftDeleteTrackingHistoryByCognitoSubParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTrackingHistoryByCognitoSub, arg.DeletedAt, arg.DeletedBy, arg.CognitoSub)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteTrackingsByCognitoSub = `-- name: SoftDeleteTrackingsByCognitoSub :execrows
UPDATE tracking
SET deleted_at = ?,
    deleted_by = ?
WHERE cognito_sub = ?
  AND deleted_at IS NULL
`

type SoftDeleteTrackingsByCognitoSubParams struct {
	DeletedAt  sql.NullTime
	DeletedBy  sql.NullString
	CognitoSub sql.NullString
}

// DO NOT USE. Superseded by internal/adapter/mysql/soft_delete.go, which is the
// only correct erasure path. This statement is kept because deleting it would
// change the generated Querier interface, and it is wrong in two ways that a
// future adopter would not notice:
//  1. It matches cognito_sub ALONE. The account-deletion cascade must match
//     cognito_sub OR user_id: a row whose sub is NULL (they predate migration
//     b17f4c2e9a30) would survive erasure while the endpoint answered 200.
//  2. It carries no COLLATE utf8mb4_bin pin. The column is case-INSENSITIVE and
//     the ids are mixed-case, so this predicate was measured on this very server
//     sweeping a DIFFERENT user's row.
//
// Account-deletion cascade. Soft delete only: stamps deleted_at/deleted_by and
// never issues DELETE.
func (q *Queries) SoftDeleteTrackingsByCognitoSub(ctx context.Context, arg SoftDeleteTrackingsByCognitoSubParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTrackingsByCognitoSub, arg.DeletedAt, arg.DeletedBy, arg.CognitoSub)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTrackingStatus = `-- name: UpdateTrackingStatus :execrows
UPDATE tracking
SET status      = ?,
    ` + "`" + `datetime` + "`" + `  = ?,
    updated_by  = ?,
    updated_at  = ?
WHERE order_id = ?
  AND deleted_at IS NULL
`

type UpdateTrackingStatusParams struct {
	Status    string
	Datetime  time.Time
	UpdatedBy sql.NullString
	UpdatedAt time.Time
	OrderID   string
}

// Advance a tracking's status. Returns the affected-row count so the caller can
// distinguish "updated" from "no such live tracking" without a second read.
func (q *Queries) UpdateTrackingStatus(ctx context.Context, arg UpdateTrackingStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrackingStatus,
		arg.Status,
		arg.Datetime,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.OrderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
