// Command server runs the Tracking HTTP service.
//
// All dependencies are wired BY HAND here — no DI container, no code generation
// for wiring, no reflection. The wiring is a function you can read top to bottom.
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"

	adapterhttp "github.com/jemartinez/3mrai/services/tracking-go/internal/adapter/http"
)

const (
	defaultPort             = "8000"
	shutdownGracePeriod     = 15 * time.Second
	serverReadHeaderTimeout = 10 * time.Second
)

func main() {
	// 12-Factor: structured logs to STDOUT, never to a file. Severity strings
	// are DEBUG/INFO/WARN/ERROR/FATAL — WARN, not WARNING.
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	// 12-Factor: configuration comes from the environment, never from a file
	// baked into the image. Env files in this repo are GENERATED by
	// `make env-file` from Terraform outputs.
	if ginMode := os.Getenv("GIN_MODE"); ginMode != "" {
		gin.SetMode(ginMode)
	} else {
		gin.SetMode(gin.ReleaseMode)
	}

	port := os.Getenv("PORT")
	if port == "" {
		port = defaultPort
	}

	router := adapterhttp.NewRouter()

	srv := &http.Server{
		Addr:              ":" + port,
		Handler:           router,
		ReadHeaderTimeout: serverReadHeaderTimeout,
	}

	// NotifyContext cancels ctx on SIGINT/SIGTERM. SIGTERM is what ECS sends
	// when it drains a task, so handling it is what makes a deploy graceful
	// rather than a burst of dropped connections.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("http server starting", slog.String("addr", srv.Addr))
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
			return
		}
		serverErr <- nil
	}()

	select {
	case err := <-serverErr:
		if err != nil {
			logger.Error("http server failed", slog.String("error", err.Error()))
			os.Exit(1)
		}
	case <-ctx.Done():
		logger.Info("shutdown signal received, draining connections")

		// A FRESH context: ctx is already cancelled, so passing it to Shutdown
		// would abort in-flight requests immediately instead of draining them.
		shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownGracePeriod)
		defer cancel()

		if err := srv.Shutdown(shutdownCtx); err != nil {
			logger.Error("graceful shutdown failed", slog.String("error", err.Error()))
			os.Exit(1)
		}
		logger.Info("http server stopped cleanly")
	}
}
